### PR TITLE
set icon name to $RESOURCE_NAME

### PR DESCRIPTION
**Pull request by darealshinji**
This way the desktop file will use the icons that are installed with xdg-icon-resource.

### CODE REVIEW

**Comment by darealshinji** [comment]
Just to clarify this: without this fix my desktop menu entries won't have an icon until the AppImage was mounted.

menu

**Comment by probonopd** [comment]
@darealshinji, the icons are not extracted from the AppImage before the AppImage is mounted (i.e., executed). So I don't understand how your change would make that icon appear before the AppImage is mounted. Also, the `desktopintegration` script is not run before the AppImage is mounted (i.e., executed). *confused*

**Comment by probonopd** [comment]
Also, I was considering to entirely drop the `desktopintegration` script now that we have `appimaged` but I take it you still think we should maintain the script?

**Comment by darealshinji** [comment]
> the icons are not extracted from the AppImage before the AppImage is mounted (i.e., executed). So I don't understand how your change would make that icon appear before the AppImage is mounted.

When I start the AppImage the first time and I agree on desktop integration, the desktop files and icons are installed into .local/share. With this change it would use the files from .local/share/icons instead of the icon from within the AppImage, which would otherwise no longer be available when the AppImage is no longer mounted.

> Also, I was considering to entirely drop the desktopintegration script now that we have appimaged but I take it you still think we should maintain the script?

So the idea is that if someone wants desktop integration, appimaged should be used, otherwise the AppImage will run without any desktop integration dialog?

**Comment by probonopd** [comment]
> When I start the AppImage the first time and I agree on desktop integration, the desktop files and icons are installed into .local/share. With this change it would use the files from .local/share/icons instead of the icon from within the AppImage, which would otherwise no longer be available when the AppImage is no longer mounted.

Using the icon from within the AppImage clearly seems to be a bug to me, I didn't intend this but I think I know where this bug came from (namely, removing the original icon extraction to the thumbnailer icon cache location).

So you are saying your PR will close #148?

> Also, I was considering to entirely drop the desktopintegration script now that we have appimaged but I take it you still think we should maintain the script?
> 
> So the idea is that if someone wants desktop integration, appimaged should be used, otherwise the AppImage will run without any desktop integration dialog?

That was what I have been considering, as some users say they don't like the dialog. Krita, for example, has not been using the dialog at all after a short test in one of their betas -- apparently users didn't unanimously like it.

**Comment by darealshinji** [comment]
It should fix #258

**Pull request merged**
