### PR TITLE
update year

### PR DESCRIPTION
**Pull request by kskarthik**
Happy New Year 2017 !

### CODE REVIEW

**Comment by probonopd** [comment]
Happy New Year!

**Comment by kskarthik** [comment]
@probonopd flightgear game lacks a binary for linux. They are stuck at ppa's for all distros. No ppa maintainers for new versions. Can you make an AppImage for it pls. I already tweeted them about us :D

**Comment by probonopd** [comment]
Indeed it would be nice to see AppImages show up in http://download.flightgear.org/builds/nightly/. 
Saikrishna Arcot seems to provide fairly recent builds for trusty which we could convert into an AppImage easily; I will give it a try.

**Comment by kskarthik** [comment]
Cool !

**Pull request merged**
