### PR TITLE
Make video responsive

### PR DESCRIPTION
**Pull request by kskarthik**

### CODE REVIEW

**Comment by kskarthik** [comment]
i strongly recommend that we need a blog http://blog.appimage.org using [hubpress](http://hubpress.io)

**Comment by probonopd** [comment]
All the different channels are growing way over what I can handle in my spare time:
* GitHub Issues
* Google+
* Twitter
* IRC
* Gitter.im
* Discourse

So I'm really hesitant to add more...

**Comment by hideout** [comment]
indeed and u forgot https://slack.com/ ;D

2016-08-16 17:05 GMT+02:00 probonopd <notifications@github.com>:

**Comment by hideout** [comment]
sorry simon gitter.im = slack ;D

2016-08-16 21:07 GMT+02:00 Ferdinand Klinzer <klinzer@gmail.com>:

**Comment by shoogle** [comment]
@probonopd all you really need to put effort into is YouTube videos to explain what AppImages are and some kind of blog to explain where the project is going. The other social media channels are just for sharing links to the blog articles and YouTube videos. Just write a post like "check out this new video about AppImages" and then copy and paste it on to each media channel. There are even 3rd party tools to do this automatically.

If I were you I would also try to outsource as much works as possible. Hopefully the [Discourse](http://discourse.appimage.org/) forum will generate enough interest to become self-maintaining. Facebook, YouTube, Google+ and other platforms allow you to appoint trusted people as admins. This gives them certain privileges (e.g. writing posts, moderating other users' posts) without you having to share the password for the main account.

**Pull request merged**
