### PR TITLE
Implemented multiarch AppImageAssistant/package

### PR DESCRIPTION
**Pull request by RazZziel**
Usage:

```
usage: package [-h] [--arch {x86_64,i686}] args [args ...]

Modes of operation:
  args = <Source AppDir> <Destination AppImage>     Create an AppImage from an AppDir
  args = <AppImage>                                 Inject the runtime into an AppImage

positional arguments:
  args

optional arguments:
  -h, --help            show this help message and exit
  --arch {x86_64,i686}  Target architecture
```

### CODE REVIEW

**Comment by RazZziel** [comment]
Comment moved from https://github.com/probonopd/AppImageKit/issues/111

---

Ported `package` argument parsing to `argparse` in order to add the `--arch` argument, I think I didn't break compatibility but please verify:

```
10:23:39 {feature/multiarch} ~/dev/AppImageKit$ ./AppImageAssistant.AppDir/package arg1 arg2 
Source AppDir: /home/raziel/dev/AppImageKit/arg1
Destination AppImage: /home/raziel/dev/AppImageKit/arg2
Should compress: True
Target architecture: (default)

10:23:44 {feature/multiarch} ~/dev/AppImageKit$ ./AppImageAssistant.AppDir/package arg1 arg2 --arch i686
Source AppDir: /home/raziel/dev/AppImageKit/arg1
Destination AppImage: /home/raziel/dev/AppImageKit/arg2
Should compress: True
Target architecture: i686

10:23:46 {feature/multiarch} ~/dev/AppImageKit$ ./AppImageAssistant.AppDir/package arg1 
Assuming I should inject a new runtime
Destination AppImage: /home/raziel/dev/AppImageKit/arg1
Should compress: False
Target architecture: (default)

10:23:49 {feature/multiarch} ~/dev/AppImageKit$ ./AppImageAssistant.AppDir/package arg1 --arch i686
Assuming I should inject a new runtime
Destination AppImage: /home/raziel/dev/AppImageKit/arg1
Should compress: False
Target architecture: i686

10:23:54 {feature/multiarch} ~/dev/AppImageKit$ ./AppImageAssistant.AppDir/package arg1 --arch i68
usage: package [-h] [--arch {x86_64,i686}] args [args ...]
package: error: argument --arch: invalid choice: 'i68' (choose from 'x86_64', 'i686')
```

Example usage:
```
10:48:05 {feature/multiarch} ~/dev/AppImageKit$ ./AppImageAssistant.AppDir/package -h
usage: package [-h] [--arch {x86_64,i686}] args [args ...]

Modes of operation:
  args = <Source AppDir> <Destination AppImage>     Create an AppImage from an AppDir
  args = <AppImage>                                 Inject the runtime into an AppImage

positional arguments:
  args

optional arguments:
  -h, --help            show this help message and exit
  --arch {x86_64,i686}  Target architecture

10:46:53 {feature/multiarch} ~/dev/AppImageKit$ ./AppImageAssistant.AppDir/package out/AppImageAssistant_5-52-g60bf4eb-i686.AppImage 
Assuming I should inject a new runtime
Embedding runtime /home/raziel/dev/AppImageKit/AppImageAssistant.AppDir/runtime...
ok
Making /home/raziel/dev/AppImageKit/out/AppImageAssistant_5-52-g60bf4eb-i686.AppImage executable...
ok
Size: 1.250000 MB

10:46:55 {feature/multiarch} ~/dev/AppImageKit$ ./AppImageAssistant.AppDir/package out/AppImageAssistant_5-52-g60bf4eb-i686.AppImage --arch=i686
Assuming I should inject a new runtime
Embedding runtime /home/raziel/dev/AppImageKit/AppImageAssistant.AppDir/arch/i686/runtime...
ok
Making /home/raziel/dev/AppImageKit/out/AppImageAssistant_5-52-g60bf4eb-i686.AppImage executable...
ok
Size: 1.250000 MB

10:46:57 {feature/multiarch} ~/dev/AppImageKit$ ./AppImageAssistant.AppDir/package out/AppImageAssistant_5-52-g60bf4eb-i686.AppImage --arch=x86_64
Assuming I should inject a new runtime
Embedding runtime /home/raziel/dev/AppImageKit/AppImageAssistant.AppDir/arch/x86_64/runtime...
ok
Making /home/raziel/dev/AppImageKit/out/AppImageAssistant_5-52-g60bf4eb-i686.AppImage executable...
ok
Size: 1.250000 MB
```

**Comment by RazZziel** [comment]
Hmmmm, problem, `AppImageAssistant` only calls `package` when it's called with three arguments

I'll implement a `package` argument for `AppImageAssistant` that runs `package` with the rest of arguments, but keep compatibility with the tree arguments thinguie

**Comment by RazZziel** [comment]
Done, easier than expected; but I just realized argparse is not included by default in CentOS... for I've copied the .py from https://pypi.python.org/pypi/argparse, but we should probably find a way to create a portable virtualenv for dependencies

**Comment by probonopd** [comment]
Would you say this is ready to merge? Would it have any side effects for projects that are currently using AppImage, such as Scribus, Subsurface, Krita, MuseScore, Pitivi, and others?

**Comment by RazZziel** [comment]
It **should** be ready to merge, but just in case I'll setup a test branch in the AppImages repo building against a test branch on this repo

**Comment by RazZziel** [comment]
Btw @shoogle in `docker/AppImageKit-x86/Dockerfile`and `docker/AppImageKit-x86_64/Dockerfile` I'm using the `--fetch-dependencies-only` you suggested in https://github.com/probonopd/AppImageKit/issues/111#issuecomment-195961651 in order to speed up build (I'm notifying just in case you have any feedback on its intented use vs actual use, and just in case I'm duplicating effort and I didn't notice. I'm using it mostly because in `build-multiarch.sh`, although I run `docker build` on every build (which will speed up developer builds but probably not travis builds), I need to invoke `docker run` many times: at least twice (first for building binaries, second one for building AppImages), and then twice more just to get the `uname -m` of the container.

@ericfont you see any problem for integrating ARM in this? A `Dockerfile` would need to be created in `docker/AppImageKit-armv7/`. IIRC you had a problem running `xorriso` inside the container: I'm still doing it, mostly for convenience and code reuse (I just need to run `build.sh AppImageAssistant AppImageExtract AppImageMonitor AppImageUpdate`, which sets up all the dependencies in the correct places and then runs xorriso), but if you think it would be worth it. I can try.

**Comment by RazZziel** [comment]
[Almost all the builds](https://travis-ci.org/RazZziel/AppImages/builds/121074106) are failing because apt can't connect to us.archive.ubuntu.com :\

**Comment by RazZziel** [comment]
Builds finished:
* [Stable AppImageKit](https://travis-ci.org/RazZziel/AppImages/builds/121335006)
* [Stable AppImageKit but with parameterized build](https://travis-ci.org/RazZziel/AppImages/builds/121334969) (same AppImageKit as before, just to check I didn't fuck up parameterizing)
* [AppImageKit from branch *testing*](https://travis-ci.org/RazZziel/AppImages/builds/121335053)

Almost everything builds, but looks like there's [a weird regression in vlc](https://travis-ci.org/RazZziel/AppImages/jobs/121335084#L398), so this is not ready to merge yet.

**Comment by RazZziel** [comment]
[Fixed](https://travis-ci.org/RazZziel/AppImages/builds/121357159)

Looks like it's ready to merge

**Comment by RazZziel** [comment]
By the way @probonopd, ir we ever want to revert to single arch binaries, it's trivial to do so by changing `build-multiarch.sh` to `build.sh` in `.travis.yml`.

Even both kinds of binaries (single and multi arch) could be generated, with different names, aulthough I think that would be complicating things for our users (can != should, but can).

**Comment by jviotti** [comment]
Has there been any further progress on this PR? We'd love to make use of this at [Etcher](http://www.etcher.io).

**Comment by probonopd** [comment]
Is this branch working for you @jviotti?

**Comment by jviotti** [comment]
Hi @probonopd ,

The branch built fine and the appImages were created fine, however I get the following error when running the i686 one:

```sh
execv error: : Exec format error
```

But maybe I did something wrong at some point. Should I include the same `AppRun` in both (only one `AppRun` seems to be built from `build-multiarch.sh`)?

**Comment by probonopd** [comment]
All components need to be the same architecture - AppRun, the runtime that gets embedded by AppImageAssistant, and the binaries and libraries inside the AppImage. It looks like you mixed some architectures?

**Comment by jviotti** [comment]
Hi @probonopd ,

I see, I was assuming that the `AppRun` built by `build-multiarch.sh` worked on both architectures. I've tried generating an i686 appImage from Ubuntu 14.04 x86_64 by passing `--arch x86_64` to `AppImageAssistant`, but passing an `AppRun` from a i686 build and the generated image works great :+1:

**Comment by probonopd** [comment]
@RazZziel not sure I completely understand this... in your example above,

```
10:46:57 {feature/multiarch} ~/dev/AppImageKit$ ./AppImageAssistant.AppDir/package out/AppImageAssistant_5-52-g60bf4eb-i686.AppImage --arch=x86_64
Assuming I should inject a new runtime
Embedding runtime /home/raziel/dev/AppImageKit/AppImageAssistant.AppDir/arch/x86_64/runtime...
ok
Making /home/raziel/dev/AppImageKit/out/AppImageAssistant_5-52-g60bf4eb-i686.AppImage executable...
ok
Size: 1.250000 MB
```
you are on a i686 machine, making a x86_64 AppImage with i686 in its name? Does that make sense?

**Comment by probonopd** [comment]
@jviotti did you get this working?

**Comment by jviotti** [comment]
@probonopd Yes, I did. I tested creating a i686 AppImage from x86_64 (didn't test the way around), and confirmed the AppImage ran fine in a i686 system.

**Comment by probonopd** [comment]
AppImageAssistant has been replaced by `appijagetool`, hence closing.

**Comment by jviotti** [comment]
@probonopd Will `appimagetool` support this functionality though?

**Comment by probonopd** [comment]
@jviotti you are looking for a 64-bit appimagetool that would create a 32-bit AppImage, correct? It's not implemented yet but shouldn't be hard to do. I opened a feature request ticket, https://github.com/probonopd/AppImageKit/issues/304

**Comment by jviotti** [comment]
Yeah, exactly. Thanks a lot, and let me know if there is something I can do to help there!

**Comment by probonopd** [comment]
Thanks @jviotti, commented in the ticket #302.

**Comment by jviotti** [comment]
@probonopd Did you reference the right ticket? #302 is about "Remove desktop integration" action.

**Comment by probonopd** [comment]
Oops, meant #304 of course :-)

**Comment by probonopd** [comment]
To everyone reading this, if you are interested in ARM builds, check out Open Build Service which can build AppImages for 32-bit and 64-bit Intel and ARM architectures. Instructions: https://github.com/probonopd/AppImageKit/wiki/Using-Open-Build-Service

**Pull request closed without merging**
