### PR TITLE
make video responsive & add news page

### PR DESCRIPTION
**Pull request by kskarthik**
* last time when i added video, i forgot to make it responsive. Now it's done.
* News page created. we can edit posts from md.html 
* since strapdown js is interrupting bootstrap, i made new page md.html which is embedded into news.html 
* works on https:// also, since i loaded strapdown.js file locally.

### CODE REVIEW

**Comment by probonopd** [comment]
Thanks @kskarthik is this hosted somewhere to try it out?

**Comment by kskarthik** [comment]
@probonopd yes https://kskarthik.github.io/app/news.html

**Comment by probonopd** [comment]
This page doesn't look right optically, the typography does not match the rest of the site. At least on Firefox... did you use any of the style sheets?

**Comment by kskarthik** [comment]
no stylesheets used

**Comment by kskarthik** [comment]
@probonopd i will pull back this PR for now. Need to do more research on this. Is it possible for you to create a subdomain for appimage.org like http://blog.appimage.org

**Pull request closed without merging**
