### PR TITLE
Added ARCH environment variable

### PR DESCRIPTION
**Pull request by hyronx**
Like discussed in #306 this adds support for an ARCH variable which can be set to skip the automatic arch detection.

### CODE REVIEW

**Comment by probonopd** [comment]
Restarted the 32-bit build, temporary failure?

**Comment by hyronx** [comment]
What is the problem? I just added an if-block and a getenv() call. There is really not much code that could break something..

**Comment by probonopd** [comment]
Looks like it was a temporary build failure unrelated to your patch; the retriggered build worked fine. Merging. Thanks!

**Comment by probonopd** [comment]
Like discussed in #306 this adds support for an `$ARCH` variable which can be set to skip the automatic arch detection.

**Pull request merged**
