### PR TITLE
Wrote a mock-appdir tool that uses mock and rpm to run on rpm-based systems

### PR DESCRIPTION
**Pull request by TC01**
I've been working on a project where we've wanted to build software and ship it out of an OpenAFS cell, and while looking into portable versions of Linux software, I discovered AppImages. I thought they were really cool, although (as a Fedora user) I was a little disappointed that a tool to make app directories only existed for Debian systems (```apt-appdir```).

I *also* thought that [Mock](https://fedoraproject.org/wiki/Mock) (a Fedora chroot-powered package builder) would be an ideal way to build AppDirs and ensure most (if not all) dependencies got included. One thing led to another, and I found myself writing a tool...

Because mock instantiates an empty chroot, I first install the X stack and systemd, which also installs the ```@buildsys-build``` group (roughly the Fedora equivalent to debian build-essential). So none of these things get bundled. But any other dependency will.

Then the RPMs that got pulled down for the requested app get copied, extracted by rpm2cpio, and the app directory gets created.

The default chroot is Fedora 20 (64-bit), because while that was recently EOL'd, it is a little old but not terribly out of date yet and also had the longest lifespan of a Fedora release for quite some time now (an entire year). But this is easily changeable.

I have tested this on a Fedora 21 desktop and it seems to work just fine. I was also able to run an output Firefox AppImage on a Debian box.

### CODE REVIEW

**Comment by TC01** [comment]
I should add: if you don't want to ship such a tool in this repo (because you're moving to use AppDirAssistant instead for such generation), then that's totally fine and I can just ship it in its own repository.

**Comment by probonopd** [comment]
Cool. I'd like to include that definitely. Two questions though: 1. Does it run on CenOS 6 or 7? 2. Would it be possible to use some sort of overlayfs in order to not have to download packages which will not end up in the AppImage? E.g., could you mount the live ISO, mount an overlayfs over it, and chroot into that? This way, the AppImages would get generated based on the live ISO and it would not be necessary to re-download the same basic packages over and again.

**Comment by TC01** [comment]
It *should* run on CentOS 6/7, I have not tested it though. (In theory, it *should* run anywhere mock can run, which includes Debian and other systems, although I will confirm this).

As for the overlayfs: hm, that's an interesting idea, I hadn't thought of that.

The reason the chroot gets wiped was to ensure a clean state when first running the tool-- in case the user had been using Mock for other things and there were other packages pre-installed. A cheap workaround would be something like this, I think:

1. Tell the user (in documentation) that for best results, they should run on a "fresh" chroot-- i.e. they need to run ```mock -r ${MOCK_TARGET} --scrub=all``` first before building. Or even make this available as a command line switch.

2. Remember which packages get downloaded for $APP.

3. After copying those RPMs out and building the app directory using their contents, purge them from the chroot. 

4. Then on subsequent runs, @base-x and @buildsys-build remain installed inside the chroot.

I could investigate doing something with a live ISO too.

**Comment by probonopd** [comment]
@TC01 How are your live ISO experiments going? Have a look at 
AppImageKit/AppImageAssistant.AppDir/testappimage where we are using unionfs-fuse to do similar things

**Comment by probonopd** [comment]
By the way, I have extended apt-appir a bit so that it also works on Fedora 23 using `dnf` instead of `apt-get`.

**Comment by probonopd** [comment]
@TC01 did you have a look at testappimage and Live ISOs? Do you think this is still relevant?

**Comment by TC01** [comment]
Argh, apologies for not posting something here sooner.

I did not get a chance to look at Live ISOs; I haven't actually needed to use AppImages since last summer and as a result never got around to getting back to this.

It's nice that ```apt-appdir``` can support Fedora now, which does make this less useful.

I think it would be ideal to use a tool like ```mock``` instead of just ```dnf```, however, to ensure that the app image is built on a "clean" system and thus includes all dependencies. (I know there is similar work underway inside Fedora to teach Fedora's buildsystem how to generate things like docker images and flatpaks composed from an RPM and all of its dependencies).

However, unless I find myself needing or wanting to use AppImages for something, I'm unlikely to spend further time on making it work myself.

So this can probably be closed, then.

**Comment by probonopd** [comment]
Thanks @TC01 for letting me know. I'm more than happy to reopen this should you or someone else have time to look into it.

**Pull request closed without merging**
