### PR TITLE
Fixes for Arch based distros

### PR DESCRIPTION
**Pull request by PHPJosh**
Hi I am developing a Arch based distro.. well really a fork that will use Appimages as the main way to install third party software and I have implemented a few fixes that allow AppImageKit to work flawlessly thus far on my In development distro and should work for any Arch based distro while at the same time supporting the rest of the distros.

If there are any concerns or other fixes i need to implement to get to merged in let me know :)

### CODE REVIEW

**Comment by probonopd** [comment]
Hi, I am merging this for now, but be aware that all python, xorriso and binary dependencies will hoefully go away soon entirely.

**Comment by PHPJosh** [comment]
ok Thank you I will keep eye on the master branch as AppImagekit is a Key part of my distro I am developing. I really look forward to more contributions

**Comment by probonopd** [comment]
Great  @PHPJosh please ping me when you have a Live ISO ready. I will run it with [SystemImageKit](https://github.com/probonopd/SystemImageKit); would be great if it will work with [SystemImageKit/boot/bin/detect_arch.sh](https://github.com/probonopd/SystemImageKit/blob/29c86cf2a939fce5ce50b14b3568482c9300f6b0/boot/bin/detect_arch.sh).

**Comment by PHPJosh** [comment]
Yep sure will. atm still building the core packages for the underlying System and syncing  to my repo before i build ISOs as the point in my distro is to provide a stable base with the common libs to be shared with all app images as I don't want  cinchOS to be a rolling release distro only thing thats going to be included with the core system is the GUI. any included Apps with cinchOS will also be app images :)

**Pull request merged**
