### PR TITLE
Add vertical social icons

### PR DESCRIPTION
**Pull request by kskarthik**
I added vertical social icons on the right of the page. It is responsive & disappears on mobile view.

vertical
ver

### CODE REVIEW

**Comment by kskarthik** [comment]
@probonopd please review this PR

**Comment by probonopd** [comment]
Thanks @kskarthik.

What do you mean by a project status page?

**Comment by kskarthik** [comment]
@probonopd  I mean to show progress of the project upto date.

Example:
 
heading: Today Appimage Version X released
date:
para: a short explanation about this release. 

I found http://strapdownjs.com/ which makes things easy than using markdown instead of html

**Comment by probonopd** [comment]
Cool! Will look into it.

**Comment by kskarthik** [comment]
@probonopd i made it. see the demo here https://kskarthik.github.io/app/news.html

**Comment by probonopd** [comment]
Doesn't seem to work on Safari 9.1

**Comment by kskarthik** [comment]
problem is https

**Pull request merged**
