### PR TITLE
Use uname for arch detection

### PR DESCRIPTION
**Pull request by hyronx**
This is a more reliable solution to get the architecture. I ran into problems by trying to package [Crystal 0.20.0](https://github.com/crystal-lang/crystal/releases/download/0.20.0/crystal-0.20.0-1-linux-x86_64.tar.gz). appimagetool chose `/embedded/lib/libyaml.so` as the library to check and got an assertion error from glib:
```
(appimagetool:14136): GLib-CRITICAL **: g_strchug: assertion 'string != NULL' failed

(appimagetool:14136): GLib-CRITICAL **: g_strchomp: assertion 'string != NULL' failed
[1]    14136 segmentation fault (core dumped)  appimagekit/out/appimagetool crystal-0.20.0-1.AppDir
```

### CODE REVIEW

**Comment by probonopd** [comment]
@hyronx thanks for the PR, however we do not want to detect the architecture of the currently running system, but of the AppDir that is about to be packaged as an AppImage. Depening on which architecture we detect, we will want to embed a runtime of the matching architecture in the future as requested in https://github.com/probonopd/AppImageKit/issues/304.

**Comment by hyronx** [comment]
Ok, I understand. Unfortunately it doesn't work this way for all programs.
At least an option for manually specifying the architecture would be great.
Maybe one of `i368`, `i686`, `x86_64`, `arm` or `arm64` with the option called `--arch`?

**Comment by probonopd** [comment]
The only situation I could imagine where we really need this is when the AppImage contains _only_ architecture indepdendent (i.e., script) code. What is your use case?

**Comment by hyronx** [comment]
Not really. If you know the architecture targeted by the application but the arch detection failed (like in my case) you could specify it manually so it works this way. Otherwise you have no way to create the AppImage because of that glib error for example...

**Comment by probonopd** [comment]
So the real issue is that we need to find out why the architecture detection failed on `libyaml.so` and how to fix that?

**Comment by hyronx** [comment]
Sounds good but maybe there are other libraries too which cause problems which could be circumvented by using an arch option. Or the user always has to create an issue in such a case and ask why it didn't work like expected, than wait until the library is supported.

**Comment by probonopd** [comment]
Would being able to set a $ARCH environment variable suit your needs? I would entertain a PR towards that end.

**Comment by hyronx** [comment]
Yes, that would be a solution, too. Thanks!

**Comment by probonopd** [comment]
I'd vote for `$ARCH` as I already have been using this in some scripts (but not yet with appimagetool).

**Comment by hyronx** [comment]
Ok, I don't have a strong opinion on that.

**Pull request closed without merging**
