### PR TITLE
Fixed scrolling in Chrome on Macs

### PR DESCRIPTION
**Pull request by hmottestad**
Smooth scrolling is already a part of OSX, iOS and Android. This pull request removes the smooth scrolling library from the code, so that each operating system can handle scrolling natively. This makes scrolling normal again in Chrome on Macs.

### CODE REVIEW

**Comment by probonopd** [comment]
Thanks @hmottestad - have you tested whether the parallax effects still work after removing this library?

**Comment by hmottestad** [comment]
@probonopd 

I didn't see any parallax effect in either your version or mine. 

You can have a look for yourself: http://hmottestad.github.io/AppImageKit/

**Comment by hmottestad** [comment]
It seems that the image responsible for the parallax effect isn't loading on my computer.

screen shot 2016-02-27 at 17 56 44

**Comment by probonopd** [comment]
I checked on your clone and it was still working for me.

**Pull request merged**
