### PR TITLE
Add sys/wait.h include to appimagetool.c for WEXITSTATUS.

### PR DESCRIPTION
**Pull request by mkrautz**
Fixes CentOS 5 build.

### CODE REVIEW

**Comment by probonopd** [comment]
Could we build in a CentOS 5 Docker container?

**Comment by mkrautz** [comment]
Doubt it'd be too useful. Extended support ends in a few months, and we're only using it to get a widely compatible libc to link against. We provide the rest of the dependencies -- we use it for nothing except for having our binaries linked against glibc-2.5. :-)

**Comment by probonopd** [comment]
> we're only using it to get a widely compatible libc to link against 

That would exactly be the point of it, yes...

**Comment by mkrautz** [comment]
Sure, I'll let you know once I have what I'm working on right now hooked up...

**Pull request merged**
