### PR TITLE
embed youtube video  below "Now What?"

### PR DESCRIPTION
**Pull request by kskarthik**
embed

### CODE REVIEW

**Comment by probonopd** [comment]
Glad that you like it. Better put it below the "Now what?" section.

**Comment by kskarthik** [comment]
sure!

**Comment by hideout** [comment]
nice talk!

**Comment by probonopd** [comment]
@kskarthik can you make the video have its own `section section-presentation section-gray` please? Then it should have its own grey background around it.

**Comment by kskarthik** [comment]
Well, @probonopd i am not so good at web development, I'm learning. I will try :smiley:

**Pull request merged**
