### PR TITLE
add favicon, effects, community menu

### PR DESCRIPTION
**Pull request by kskarthik**

### CODE REVIEW

**Comment by probonopd** [comment]
Can you please post a link to preview this? Thanks

**Comment by kskarthik** [comment]
Here you go https://rawgit.com/kskarthik/AppImageKit/gh-pages/index.html

**Comment by probonopd** [comment]
That is a neat trick with rawgit :-) Not sure I like the animations though, a bit much for my taste and a bit much overhead?

**Comment by kskarthik** [comment]
so, what do you suggest ? i will remove the animations for distro's

**Comment by probonopd** [comment]
Pls. just add the community w/o the animations. Animations that appear once when the user scrolls to the corresponding area might be cool...

**Comment by kskarthik** [comment]
i got it. the community nav is as you said. I will make the rest on hover only

**Comment by kskarthik** [comment]
Done!

**Comment by kskarthik** [comment]
@probonopd I have done necessary changes

**Comment by probonopd** [comment]
Looking at the diff, I see many unrelated changes. Can you please send a PR that only adds the community menu item and otherwise changes nothing? Thanks!

**Comment by kskarthik** [comment]
I removed animations. You can see demo here https://rawgit.com/kskarthik/AppImageKit/gh-pages/index.html Just kept effects on hover

**Comment by probonopd** [comment]
The diff is still much larger than need be. https://patch-diff.githubusercontent.com/raw/probonopd/AppImageKit/pull/216.diff

The only change that I would like to make is to add the word "Community" in the top nav and link it to the Discourse community.

**Comment by kskarthik** [comment]
don't require hover effects ?

**Comment by probonopd** [comment]
No, I think it's a bit too much

**Comment by kskarthik** [comment]
ok, i will be back with a new PR

**Pull request closed without merging**
